services:
  # Server 1
  MskLanSrv1:
    image: ghcr.io/melkortf/tf2-competitive
    restart: always
    env_file:
      - .env
    environment:
      - SERVER_HOSTNAME=[MoscowLAN] Server 1
      - STV_NAME=[SourceTV] 1
      - PORT=27015
      - CLIENT_PORT=27016
      - STEAM_PORT=27018
      - STV_PORT=27020
    command: "+sv_pure 2 +map cp_badlands +maxplayers 12 +sv_lan 1 +sm_map_download_base http://changeme:8080/maps"
    volumes:
      - ./overrides/entrypoint.sh:/home/tf2/server/entrypoint.sh:ro
    network_mode: host

  # Server 2
  MskLanSrv2:
    image: ghcr.io/melkortf/tf2-competitive
    restart: always
    env_file:
      - .env
    environment:
      - SERVER_HOSTNAME=[MoscowLAN] Server 2
      - STV_NAME=[SourceTV] 2
      - PORT=27025
      - CLIENT_PORT=27026
      - STEAM_PORT=27028
      - STV_PORT=27030
    command: "+sv_pure 2 +map cp_badlands +maxplayers 12 +sv_lan 1 +sm_map_download_base http://changeme:8080/maps"
    volumes:
      - ./overrides/entrypoint.sh:/home/tf2/server/entrypoint.sh:ro
    network_mode: host

  # Server 3
  MskLanSrv3:
    image: ghcr.io/melkortf/tf2-competitive
    restart: always
    env_file:
      - .env
    environment:
      - SERVER_HOSTNAME=[MoscowLAN] Server 3
      - STV_NAME=[SourceTV] 3
      - PORT=27035
      - CLIENT_PORT=27036
      - STEAM_PORT=27038
      - STV_PORT=27040
    command: "+sv_pure 2 +map cp_badlands +maxplayers 12 +sv_lan 1 +sm_map_download_base http://changeme:8080/maps"
    volumes:
      - ./overrides/entrypoint.sh:/home/tf2/server/entrypoint.sh:ro
    network_mode: host

  # MGE Server
  MskLanMGE:
    image: ghcr.io/melkortf/tf2-mge
    restart: always
    env_file:
      - .env
    environment:
      - SERVER_HOSTNAME=[MoscowLAN] MGE
      - PORT=27045
      - CLIENT_PORT=27046
      - STEAM_PORT=27048
      - STV_PORT=27050
    command: "+sv_pure 2 +map mge_oihguv_sucks_a12 +maxplayers 24 +sv_lan 1 +sm_map_download_base http://changeme:8080/maps +mp_timelimit 0"
    volumes:
      - ./overrides/entrypoint.sh:/home/tf2/server/entrypoint.sh:ro
    network_mode: host

  # Ultiduo
  MskLanUD:
    image: ghcr.io/melkortf/tf2-competitive
    restart: always
    env_file:
      - .env
    environment:
      - SERVER_HOSTNAME=[MoscowLAN] Ultiduo
      - STV_NAME=[SourceTV] Ultiduo
      - PORT=27055
      - CLIENT_PORT=27056
      - STEAM_PORT=27058
      - STV_PORT=27060
    command: "+sv_pure 2 +map cp_badlands +maxplayers 4 +sv_lan 1 +sm_map_download_base http://changeme:8080/maps +mp_timelimit 0"
    volumes:
      - ./overrides/entrypoint.sh:/home/tf2/server/entrypoint.sh:ro
    network_mode: host

# Зеркало Logs.tf
  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "8081:8081"
    volumes:
      - ./overrides/Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped

  # FastDL
  fastdl:
    image: nginx:alpine
    restart: always
    volumes:
      - ./fastdl:/usr/share/nginx/html:ro
    ports:
      - "8080:80"

  # Mumble
  mumble-server:
    build:
      context: ./mumble-server
      dockerfile: Dockerfile
    container_name: mumble-server
    hostname: mumble-server
    restart: on-failure
    ports:
      - 64738:64738
      - 64738:64738/udp
